version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN} # This will be loaded from .env
    env_file:
      - .env
    restart: unless-stopped
