import discord
from discord.ext import commands
from discord import app_commands
import random

class drafter_cog(commands.Cog):
  def __init__(self, client: commands.Bot):
    self.client = client
    self.armello_list = ["Thane, the Winter Wolf", "Amber, the Far Seeker", "Mercurio, the Grinning Blade", "Sana, the Forest Sister", "River, the Howling Arrow", "Barnaby, the Screwloose", "Zosha, the Whirlwind", "Brun, the Oakbreaker", "Magna, the Unbroken", "Elyssia, Wardress of Warrens", "Sargon, the Death Teller", "Ghor, the Wyldkin", "Horace, the Iron Poet", "Scarlet, the Bandit King", "Sylas, the Fisher of Souls", "Twiss, the Little Lightpaw", "Hargrave, the Thunder Earl", "Griotte, the Butcher Baroness", "Fang, the Exiled", "Yordana, the Devourer", "Agniya, the Revenant", "Nazar, the Maniac", "Oxana, the Sentinel", "Volodar, the Wormchanter"]
    self.civ_list = ["Akkad - Sargon\nAbility: The Great Unification - +3 Culture, +2 Happiness and +1 Production from conquered cities. Great Generals grant nearby Units a +15% Combat Bonus when initiating combat with enemy Cities.\nBuilding: Akkadian Library - Replaces the Library. Provides +1 additional Science and does not require Gold maintenance. Costs less to produce (40 hammers vs. 50).\nUnit: Laputtu - Replaces Spearmen. 3 Movement (vs. 2). Units that start their turn on the same tile as this unit copy this unit’s Movement stat.\nBias: None"
           , "Aksum - Ezana\nAbility: Saint Elesbaan's Blessing - Upon founding a Religion, your cities immediately follow it. Your cities do not exert Religious pressure.\nImprovement: Rock-Hewn Church - Replaces Quarries. Available at Mining instead of Masonry. Provides +2 Faith and +1 Production. +1 Faith at Theology. (Note that Cities captured by Aksum will not have their Quarries converted.)\nBuilding: King Ezana’s Stele - Replaces the National Epic. Requires a Shrine in every city to build instead of Monuments. Provides +3 Culture and +4 Faith in addition to its base yields. All Shrines in the empire provide an additional +2 Food, +1 Production, +1 Gold and +1 Faith.\nBias: Hill"
           , "America - Washington\nAbility: Manifest Destiny (unchanged) - Military Land Units gain +1 Sight.Gold costs for purchasing territory are halved.\nUnit: Minuteman (unchanged) - Replaces Musketmen. Ignores terrain costs, arrives trained with Drill I (+15% bonus in Rough terrain), and earns 100% of foe’s Strength as points towards a Golden Age from kills.\nUnit: Pioneer - Replaces the Settler. Has the same combat and movement properties as the Scout (preventing instant capture) and may Settle.\nBias: None"
        , "Arabia - Harun al-Rashid\nAbility: Ships of the Desert (unchanged) - Caravans can reach Cities +50% further away. Trade Routes apply Religious Pressure twice as effectively. Receive twice as many Oil resources when improved.\nUnit: Camel Archer - Replaces the Knight. A Mounted Ranged Unit with 20 Ranged Strength (from 21) and 14 Combat Strength (from 17, vs. 20). Receives no penalty when initiating combat with an enemy City.\nBuilding: Bazaar (unchanged) - Replaces the Market. Yields an additional +1 Gold and provides +2 Gold to all Oasis and Oil resource tiles in the City. Gain a copy of every Luxury resource connected in the City. Trade Routes sent by rival Civilizations to Cities with a Bazaar will generate an additional +1 Gold for both players.\nBias: Desert"
, "Argentina - Eva Perón\nAbility: Pride of the People - Construct Pastures and Farms twice as fast.\nUnit: Gaucho - Replaces the Knight. Receives a 50% chance to withdraw from Melee attacks. Flanking bonuses are tripled. Capable of building Pastures and Farms.\nBuilding: Ocupada Estable - Gain +1 Food from Pasture resources and +1 Production from Maize in addition to the regular benefits of the Stable.\nBias: None"
, "Armenia - Tiridates III\nAbility: Splendor of the Caucasus - +1 Food, +2 Production and +1 Gold from Mountains (including mountainous Natural Wonders - i.e. Kilimanjaro, Uluru, Mt. Fuji, Mt. Sinai, Mt. Kailash, Rock of Gibraltar and Sri Pada).\nUnit: Sparapet - Replaces Horsemen. Requires 80 Production and 2 Horse resources. Boasts a mighty 17 Combat Strength (vs. 12) and grants the Great General Combat Bonus to nearby allies. Does not obsolete.\nBuilding: Darbas - Replaces the Observatory. In addition to the typical perks, provides +4 Culture in the City and +2 Culture on Mountain tiles and Wonders for a total of +5 Science and +2 Culture on those tiles.\nBias: Hill, Avoid Jungle"
, "Assyria - Ashurbanipal\nAbility: Siege Warfare - Siege Units receive +1 Movement. Receive a free Great Writer at Philosophy, and receive a free Great Work of Writing upon completion of the Royal Library in the Capital.\nBuilding: Royal Library - Replaces the Library. Provides an additional +1 Culture and Science and provides +15 (from 10) XP to Units trained in the City when its Great Work of Writing slot is filled.\nUnit: Siege Tower (unchanged) - Replaces the Catapult. A Melee Siege Unit with 12 Strength (vs. 7) only capable of combat with enemy Cities. Arrives trained with Cover I (+33% bonus defending against Ranged attacks). When adjacent to an enemy City, Units within 2 tiles of the Siege Tower gain a +50% Combat Bonus when initiating combat with that City.\nBias: Avoid Tundra"
, "Australia - Henry Parker\nAbility: Dreamtime - +5 Faith from Natural Wonders. Gain 10 Faith upon discovering a Natural Wonder.\nUnit: Ngangkari - Replaces the Worker. 3 Movement (vs. 2), receives an additional +1 Movement while embarked, and arrives with Medic I and II (adjacent allies heal an additional +10 HP while Fortified).\nBuilding: Convict Penitentiary - Replaces the Constabulary. Available at Machinery (instead of Banking). In addition to slowing the rate of Technology theft, provides +1 Gold and Production, and +5% Gold and Production in the City. Requires no Gold maintenance and is appreciably cheaper to construct (80 hammers vs. 106).\nBias: Coast"
, "Austria - Maria Theresa\nAbility: Diplomatic Marriage (unchanged) - May spend Gold to annex a City-State that has been your ally for at least 5 turns.\nUnit: Hussar (unchanged) - Replaces Cavalry. +1 Sight and Movement and is 50% more effective at Flank attacks (bonus from each ally adjacent to foe increases from +10% to +15% per ally).\nBuilding: Coffee House - Replaces the Windmill. Available at Printing Press (instead of Economics). In addition to the typical perks, provides a +5% Production bonus and a +25% Great Person generation bonus in the City. Much cheaper to construct (100 hammers from 167, vs. 167).\nBias: Hill"
, "Ayyubids - Saladin\nAbility: Justice of Saladin - Receive a free Burial Tomb in each City you conquer. Workers construct improvements +25% faster. (The Burial Tomb is a unique building of Egypt that replaces the Temple. If the Temple in a captured City survives, the City will house both buildings.)\nBuilding: Madrasah - Replaces the University. In addition to the typical perks, provides +2 Faith in the City; +1 Science from Flood Plains, +2 Science from Oases.\nUnit: Mamluk - Replaces the Knight. Gains a +50% bonus vs. Melee units, +25% vs. Gunpowder units. Slightly more expensive to produce (85 hammers vs. 80).\nBias: Desert"
, "Aztecs - Montezuma\nAbility: Sacrificial Captives (unchanged) - Earn 100% of foe’s Strength as Culture from kills.\nBuilding: Floating Gardens - Replaces the Watermill. In addition to the typical perks, provides +10% Food (from +15%) in the City and each Lake tile in the City provides an additional +1 (from +2) Food. In addition to Rivers, the Floating Gardens may also be constructed when adjacent to Lakes. Costs less Gold maintenance (1 Gold vs. 2).\nUnit: Jaguar (unchanged) - Replaces the Warrior. Gains a +33% Combat Bonus in Forests and Jungles, heals 25 HP from kills, and moves unimpeded through Forests and Jungles. (These promotions are retained upon upgrade.)\nBias: Jungle"
, "Babylon - Nebuchadnezzar II\nAbility: Ingenuity - Receive a free Great Scientist in the Capital when you discover Philosophy (previously Writing). Earn Great Scientists +25% (from +50%) faster.\nBuilding: Walls of Babylon (unchanged) - Replaces Walls. Boosts City Strength by +6 (vs. 5) and raises City health by +100 (vs. 50). Cheaper to construct (44 hammers vs. 50).\nUnit: Bowman (unchanged) - Replaces the Archer. 7 Melee Strength (vs. 5) and 9 Ranged Strength (vs. 7).\nBias: Avoid Tundra"
, "Belgium - Leopold II  \nAbility: Colonialist Riches - +1 Production from Plantations. +1 Gold from Strategic Resources.\nBuilding: Stade - Replaces Zoo. In addition to the typical perks, provides an additional +1 Happiness, Culture, and Gold, and does not require Gold maintenance. Cheaper to construct (100 hammers vs. 120). Does not require a Colosseum to be built.\nUnit: Force Publique - Replaces Great War Infantry. 51 Strength (vs. 50), arrives with Drill I (+15% bonus in Rough terrain) and Charge (+33% bonus vs. wounded Units).\nBias: None"
, "Boers - Stephanus Johannes Paulus Kruger\nAbility: The Great Trek - +1 Food from non-freshwater Farms, +1 Culture from Farms after the discovery of Fertilizer.\nBuilding: Staatsmuseum - Replaces the Opera House. Provides +1 additional Culture and houses an Artist Specialist slot. Cheaper to construct (117 hammers vs. 134).\nUnit: Voortrekker - Replaces Great War Infantry. Gains a +25% Bonus when foes initiate combat against this Unit. Heals completely from kills. Capable of building Farms in 2 turns. Slightly cheaper to construct (200 hammers vs. 210).\nBias: None"
, "Bolivia- Tata Belzu\nAbility: Revolución Nacional - Expending a Great Artist improves the yield of Mines with +1 Production and expending a Great Writer improves them with +1 Food instead. (When one yield has already been chosen, choosing the opposite will swap them instead of stacking. This ability cannot be triggered by unique Artist or Writer replacements.)\nGreat Person: Comparsa Folklorica - Replaces the Great Musician. Moves further (4 Movement vs. 2) and may be consumed to spread Tourism, begin a Golden Age, or gain a large amount of Culture.\nUnit: Colorado - Replaces the Anti-Tank Rifle. 40 Strength (vs. 30). Available at Dynamite. Only receives a +100% Bonus vs. Armored Units (vs. 200), but gains +2 Strength for every 5 points of excess Happiness in the empire. (Rounds up. Updates when a unit is moved or when a new turn begins.)\nBias: Hill"
, "Brazil - Pedro II\nAbility: Carnival! - Output +100% more Tourism and generate Great Artists, Writers, and Musicians +100% (from 50%) faster during Golden Ages.\nUnit: Pracinha - Replaces Infantry. 80 Strength (from 70, vs. 70) and earns 100% of foe’s Strength as points towards a Golden Age from kills. Gains a +20% Combat Bonus outside of friendly territory.\nImprovement: Brazilwood Camp - Available at Bronze Working (instead of Machinery). May be constructed on Jungle OR Forest tiles. Provides +1 Production. Gains +2 Gold at Machinery and +2 Culture at Acoustics.\nBias: Jungle"
, "Brunei - Bolkiah\nAbility: Sea Nomads - All Naval Units may heal outside friendly territory and pay 33% less Gold maintenance. Melee Naval Units can create improvements on Coast and Ocean tiles.\nBuilding: BMPC Plant - Replaces Oil Refineries. In addition to the typical perks, provides +3 Gold and +5 Production. Doesn’t require nearby Oil to build. Upon completion, provides 2 Oil resources.\nImprovement: Kampong Ayer - Requires Optics. May be built on any Coastal tile adjacent to land tiles. Provides +1 Food, Culture and Gold. +1 Production at Navigation, and +1 additional Culture at Flight.\nBias: Coast"
, "Bulgaria - Asparukh Khan\nAbility: Cyrillic Script - Writer Specialists provide +5 Science; Science buildings provide +1 Culture.\nUnit: Konnitsa - Replaces the Knight. Similar to an Impi, performs a Ranged attack when initiating combat.\nBuilding: Khambar - Replaces Granary. Cheaper to construct (32 hammers vs. 40). In addition to the typical perks, yields +1 Gold from Wheat and Cattle resources.\nBias: None"
, "Burma - Anawrahta\nAbility: Pyu City States - +1 Happiness in every City.\nUnit: Akyat Cannon - Replaces the Cannon, but is available at Gunpowder (instead of Chemistry). Identical combat capabilities and production cost to the Trebuchet, but wields 3 Range instead of 2.\nBuilding: Kyawwat - Replaces Stoneworks. In addition to the typical perks, the Kyawwat extends its yield bonuses to Salt and Iron resources and does not require any resources within the City to construct.\nBias: None"
, "Byzantium - Theodora\nAbility: Patriarchate of Constantinople (unchanged) - Choose an additional Pantheon, Follower, Founder or Enhancer Belief when founding a Religion.\nBuilding: Hippodrome - Replaces Amphitheater. Slightly less costly to produce (63 hammers vs. 67). In addition to the typical perks, also provides +2 Faith and +1 Happiness in the City.\nUnit: Cataphract (unchanged) - Replaces Horsemen. 15 Strength (vs. 12), but 3 Movement (vs. 4). Able to receive defensive Terrain Bonuses and is penalized slightly less for attacking Cities (-25% vs. -33%).\nBias: None (no longer Coastal)"
, "Canada - John A. MacDonald\nAbility: Canadian Fur Trade - +2 Gold from Camps, +2 Gold and +1 Culture from Lake tiles.\nUnit: Combat Engineer - Replaces Rifleman. Available at Industrialization. Identical Strength, but +1 Movement (3 vs. 2). May construct Roads, Railroads and Forts, and clear Forests, Jungles and Marsh tiles.\nBuilding: Tim Horton’s - Replaces Stock Exchange. In addition to the typical perks, provides +2 Happiness in the City and +1 Gold to river tiles worked by this City. Significantly cheaper to construct (200 hammers vs. 280).\nBias: None"
, "Carthage - Dido\nAbility: Phoenecian Heritage - All Coastal Cities receive a free Harbor. Units may cross mountains, receiving 50 HP damage if they end their turn on one. (The ability to cross mountains is no longer tied to earning a Great General). (Note: Harbors will only form City Connections after the discovery of the Wheel, but will still provide the appropriate Gold.)\nBuilding: Cothon - Replaces Lighthouse. +1 Food in the City in addition to the typical perks.\nUnit: African Forest Elephant - Replaces Horsemen, but does not require Horses to construct. 14 Strength (vs. 12), but 3 Movement (vs. 4). Possesses the Feared Elephant (enemy Units adjacent to this Unit receive a -10% combat penalty), Great Generals II (earns Great General points faster) promotion and Hannibal’s Charge (+20% Strength when initiating combat from a higher elevation than foe; enemy Units will retreat if they receive more damage than this Unit, this Unit deals +50% damage to defenders incapable of retreat).(Feared Elephant will not stack.)\nBias: Coast\n"
, "Celts - Boudicca\nAbility: Druidic Lore - Cities with an adjacent unimproved Forest tile generate +1 Faith, increasing to +2 Faith with three adjacent tiles.\nBuilding: Silversmith - Replaces the Mint. Provides +2 Production and +1 Gold (vs. +2 Gold) and does not require resources to construct, but retains the typical perks of a Mint. Less costly to produce (50 hammers vs. 66).\nUnit: Pictish Warrior - Replaces Spearmen. Earn 100% of your foe’s Combat Strength as Faith from kills (previously 50%). Gains a +20% Combat Bonus outside of friendly territory and may pillage without movement penalties.\nBias: Forest"
, "Chile - Bernardo O’ Higgens\nAbility: By Reason or By Force - Claim all surrounding neutral tiles upon the completion of Fishing Boat or Drydock improvements. Receive a free Great Admiral at Compass. Friendly Melee & Gunpowder Units inflict a -25% Combat Penalty to adjacent enemy Naval Units; Melee Naval Units inflict this penalty to adjacent enemy Land Units. (Embarked Units do not apply these penalties.)\nBuilding: Cooperative - Replaces the Factory. In addition to the typical perks, provides +2 Happiness and houses an additional Engineer Specialist (3 vs. 2). Does not require Gold maintenance. Ideologies are unlocked for Chile after the completion of only 1 Cooperative (compared to 3 Factories).\nUnit: Cardoen - Replaces the Helicopter Gunship. Stronger (85 Strength vs. 70). In addition to the typical bonuses, the Cardoen is capable of attacking and capturing Cities and receives a +100% Combat Bonus defending against ranged attacks.Bias: Coast"
, "China - Wu Zetian\nAbility: Art of War (unchanged) - Great Generals provide an additional +15% Combat Bonus to nearby Units and are generated +50% faster.\nBuilding: Paper Maker (unchanged) - Replaces the Library. Requires no Gold maintenance and provides +2 Gold.\nUnit: Chu-Ko-Nu (unchanged) - Replaces Crossbowmen. Weaker at base (14 Strength vs. 18), but may attack twice each turn.\nBias: None"
, "Colombia - Simon Bolivar\nAbility: Independence of the People - +1 Food and Gold from Lumber Mills. Lumber Mills receive an additional +1 Science at Chemistry. Earn 100 Golden Age points when capturing or liberating Cities.\nBuilding: Cacicazgo - Replaces the Granary. In addition to the typical perks, provides +1 Production and Gold and allows the City to send Production through Trade Routes (as a Workshop would). Doesn’t require Gold maintenance. Slightly more expensive to construct (44 hammers vs. 40).\nUnit: Llanero - Replaces Cavalry. Capable of receiving defensive terrain bonuses and Fortifying.\nBias: Forest, Plains"
, "Cuba - Fidel Castro\nAbility: ¡Viva la Revolución! - Receive +1 Culture per turn in your Capital for every 5 Culture per turn generated in the Capital of Civilizations you’ve met. Upon selecting your first Ideology Tenet, receive 2 Guerrilleros in the Capital. Receive -50% less Unhappiness from Ideology pressure.\nUnit: Guerrillero - Replaces Great War Infantry. Available to produce only after the adoption of Cuba’s first Ideology Tenet (as opposed to Replaceable Parts). Weaker (44 Strength vs. 50), but boasts 3 Movement (vs. 2) and can be built for significantly less (176 hammers vs. 221).\nBuilding: Dance Hall - Replaces the Opera House. In addition to the typical perks, the Dance Hall provides +1 Happiness, +4 Culture, and +15% Production towards military Units in the City when its Great Work slot is filled. (This bonus is updated at the start of every turn.) Cheaper to construct (100 hammers vs. 134).\nBias: None"
, "Denmark - Harald Bluetooth\nAbility: Viking Fury - Embarked Units gain +1 Movement and may disembark for only 1 Movement. Melee Units pillage without movement penalties. +1 Production from Fish resources.\nUnit: Berserker (unchanged) - Replaces Longswordsmen. Available at Metal Casting instead of Steel. 3 Movement (vs. 2) and ignores penalties for attacking over rivers or while embarked.\nUnit: Longship - Replaces Trireme. 6 Movement (vs. 4). Embarked Units that begin their turn on the same tile as a Longship are granted 6 Movement for that turn. (This Movement bonus is retained after disembarkation. Promoted Longships with bonus Movement will also confer this bonus to the embarked Unit.)\nBias: Coast"
, "Egypt - Ramesses II\nAbility: Monument Builders - +15% (from 20%) Production towards the construction of World Wonders.\nBuilding: Burial Tomb (unchanged) - Replaces the Temple. In addition to the typical perks, provides +2 Happiness and does not require Gold maintenance. Cities with a Burial Tomb double the amount of Gold plundered for the conqueror.\nUnit: War Chariot (unchanged) - Replaces the Chariot Archer. 5 Movement (vs. 4) and does not require Horse resources to construct.\nBias: Desert"
, "England - Elizabeth\nAbility: Sun Never Sets - English Naval Units receive +2 Movement. Receive an additional Spy upon entering the Renaissance. Constabularies and Police Stations are built twice as fast and provide +1 Happiness.\nUnit: Longbowman - Replaces Crossbowmen. 12 Melee Strength (vs. 13) and 18 Ranged Strength (from 17, vs. 18), but wields 3 Range (vs. 2).\nUnit: Ship of the Line - Replaces the Frigate. +1 Sight. 25 Combat Strength (from 30, vs. 25) and 30 Ranged Strength (from 35, vs. 27). (The Ship of the Line has 5 Movement at base (vs. a Frigate’s 6), increasing effectively to 7 due to Sun Never Sets.)\nBias: Coast"
, "Ethiopia - Haile Selassie\nAbility: Spirit of Adwa (unchanged) - Ethiopian Units gain a +20% Bonus in combat with Civilizations with more Cities than Ethiopia.\nBuilding: Stele (unchanged) - Replaces the Monument. In addition to the Culture yield, provides +2 Faith.\nUnit: Mehal Sefari - Replaces Riflemen. 35 Strength (from 34, vs. 34). Arrives trained with Drill I (+15% Bonus in Rough terrain) and gains Strength according to distance from the Capital, peaking at +30% when the Mehal Sefari is stationed inside the Capital and decreasing by -3% per tile away. Cheaper to produce (134 hammers vs. 150).\nBias: None"
, "Finland - Mannerheim\nAbility: Finnish Mobility - All Melee and Mounted Units receive a +50% increased flanking bonus (+15% per ally adjacent to foe vs. 10%). +1 Culture from unimproved Forest tiles.\nUnit: Sissi - Replaces the Machine Gun. 3 Movement (vs. 2). Ignores terrain cost and receives a +25% Combat Bonus vs. Armored Units. Does not spend movement when pillaging tiles, but cannot attack twice.  60 Ranged Strength (vs. 50), 50 Melee Strength. Cheaper to construct (234 hammers vs. 260).\nBuilding: Sauna - Replaces the Shrine. +2 Culture from Lake tiles. Units trained in Cities with a Sauna heal +10 HP inside friendly territory.\nBias: None"
, "France - Napoleon\nAbility: City of Light - +1 Culture in the Capital, increasing by an additional +15 upon the discovery of Acoustics. Theming bonuses are doubled in the Capital.\nImprovement: Chateau - Provides +2 Science, +2 Culture and +1 Gold, increasing by +1 Culture and +2 Gold at Flight, and +1 Science after adopting the Free Thought policy. Provides the same defensive bonus as a Fort (+50% bonus when foe initiates combat). Chateaus must be constructed adjacent to a luxury resource, non-adjacent to another Chateau, and not atop an existing Resource tile. (Resources discovered after the construction of the Chateau will provide their yield bonus to the tile, but the Chateau will not ‘connect’ those resources.)\nUnit: Musketeer (unchanged) - Replaces Musketmen. 28 Strength (vs. 24). That’s it.\nBias: None"
, "Franks - Charlemagne\nAbility: Holy Roman Empire - +1 Faith from Farms. Frankish Units receive +25% additional Movement when traveling along friendly and neutral Roads and Railroads.\nBuilding: Mead Hall - Replaces the Colosseum. Provides an additional point of Happiness (3 vs. 2) and a bonus +1 Culture.\nUnit: Seaxman - Replaces Longswordsmen. Available at Chivalry instead of Steel. 22 Strength (vs. 21). Arrives trained with the Cover I (+33% bonus defending against ranged attacks) and Amphibious (attack from the sea or over rivers without penalty) promotions. Almost negligibly cheaper to construct (76 hammers vs. 80).\nBias: None"
, "Gaul - Vercingetorix\nAbility: Oppidum of Bibracte - Receive a Murus Gallicus in the Capital upon the discovery of Mining.\nBuilding: Murus Gallicus - Replaces Walls. Slightly cheaper (44 Production vs. 50) and better defense (+6 vs. +5). +1 Production and +1 Happiness; +1 additional Production after researching Metal Casting.\nUnit: Noble Swordsman - Replaces Longswordsmen. 20 Strength (vs. 21). Gains a +25% Combat Bonus when initiating combat and a +50% Bonus in Forests. Does not require Iron resources. Becomes obsolete at Rifling (instead of Gunpowder) and upgrades into Riflemen."
, "Georgia - Tamar (new! v31)\nAbility: Ecclesiastical Architecture - Buildings unlocked by religious beliefs (except Houses of Worship) are built using Production instead (cost equal to 33% of the required Faith); these buildings provide +2 Production.\nBuilding: Tsikhe - Replaces Walls. In addition to typical defensive perks, provides +3 Faith, and +1 Culture from Strategic Resources (e.g. Horses, Iron). Units trained in this City earn Golden Age points from kills.\nUnit: Khevsur - Replaces Swordsmen. Arrives at Guilds technology instead of Iron Working, but ignores terrain movement costs as a Scout would, and receives a +33% Combat Bonus during Golden Ages.\nBias: None"
, "Germany - Bismarck\nAbility: Precision Engineering - +1 Science and Production from Workshops, Windmills, Factories and Hydro Plants. +33% faster Great Engineer generation.\nBuilding: Hanse (unchanged) - Replaces Banks. In addition to the typical perks, gain +5% Production in the City for every Trade Route your empire currently maintains with a City-State.\nUnit: Panzer (unchanged) - Replaces the Tank. 80 Strength (vs. 70) and 6 Movement (vs. 5).\nBias: None"
, "Golden Horde - Batu Khan\nAbility: Golden Conquest - Units are +50% more effective at intimidating City-States. Puppeted Cities provide +50% Production, Gold, and Science, and generate -33% less Unhappiness.\nBuilding: Yam Route - Replaces Caravansaries. Available at The Wheel instead of Horseback Riding. Retains Trade Route perks but doesn’t provide Gold, instead providing +3 Science. Allows Airlifting between Cities with Yam Routes.\nUnit: Ulan - Replaces Pikemen. Stronger than its counterpart (17 Strength vs. 16). Behaves as a Mounted Unit and requires a Horse resource. 4 Movement (vs. 2). Arrives with Charge (+33% bonus against wounded foes) and does not receive a penalty in combat with Cities.\nBias: None"
, "Goths - Alaric I\nAbility: Drauhtinon - Melee and Gunpowder units receive +1 Movement.\nUnit: Gadrauht - Replaces Longswordsman. 22 Strength (vs. 21). Cheaper to produce (72 hammers vs. 80) and does not require Iron to train.\nMoves along enemy roads as if they were friendly roads.\nImprovement: Harjis - Available at Mining. Must be adjacent to a Luxury resource (but not on a Luxury resource) and non-adjacent to another Harjis. Provides +1 Production. Gains an additional +1 Production upon the discovery of Iron Working, Gunpowder and Dynamite.\nBias: None"
, "Greece - Pericles\nAbility: Hellenic League (unchanged) - City-State Influence degrades half as slowly and recovers at twice the typical rate.\nBuilding: Odeon - Replaces the Amphitheater. Provides +4 Culture (vs. 2), +1 Gold, and does not require Gold maintenance. Houses a slot for a Great Writer specialist.\nUnit: Hoplite (unchanged) - Replaces Spearmen. 13 Strength (vs. 11).\nBias: None (previously Mixed)."
, "Hittites - Muwatallis\nAbility: Bronze and Iron - +1 Gold from Mines. Start with Mining Technology.\nBuilding: Lion’s Gate - Replaces Walls. Cheaper to construct (40 hammers vs. 50). In addition to the typical defensive perks, provides +2 Gold and +2 Culture in the City.\nUnit: Heavy Chariot - Replaces the Chariot Archer. Identical Ranged Strength and 3 Movement (vs. 4), but 10 Melee Strength (vs. 5). Gains a +20% defensive bonus when enemies initiate combat.\nBias: None"
, "Huns - Attila\nAbility: Scourge of God (unchanged) - Start with Animal Husbandry Technology. +1 Production from all Pastures. Raze Cities at double speed and borrow City names from rival Civilizations.\nBuilding: Qara U’y - Replaces the Stable. In addition to the typical perks, yields  +1 Faith from Horses. Provides 2 Horse Resources for the empire upon completion.\nUnit: Horse Archer - Replaces the Chariot Archer. Greater Melee Strength (7 vs. 6), receives no movement penalty in Rough terrain, and arrives with Accuracy I (+15% bonus in Open terrain). Requires Horses to construct. (In Brave New World, this Unit did not require Horses.)\nBias: Avoid Forest, Jungle"
, "Hungary - András II\nAbility: Verszerzodes - Walls, Castles, Arsenals and Military Bases provide +1 Production and Culture. May construct up to 2 Palaces.\nUnit: Black Arquebusier - Replaces Musketmen. Identical strength, but is capable of setting up to perform Ranged attacks (similar to a Siege Unit). Arrives with Accuracy I (+15% bonus in Open terrain). Slightly cheaper to produce (90 vs. 100). (Despite Accuracy typically denoting a bonus for Ranged units only, this bonus and other similar bonuses will apply to both Melee and Ranged attacks from this Unit.)\nBuilding: Orszaggyules - Replaces the Palace. In addition to the regular bonuses of a Palace, provides +25% faster Great Person generation and +10% Production towards buildings in the City. Receive this building in the original Capital. Upon the discovery of Mathematics, a second Orszaggyules may be constructed in another City (for 67 hammers); this City becomes the new Capital of the empire. The original Orszaggyules may be sold and reconstructed to move this designation back; the Capital is located wherever the last Orszaggyules was constructed.\nBias: None"
, "Inca - Pachacuti\nAbility: Great Andean Road (unchanged) - Units ignore terrain costs moving through Hills. No Gold maintenance is paid for tile improvements in Hills, and half the Gold is paid for improvements elsewhere.\nImprovement: Terrace Farm (unchanged) - May only be constructed in Hills. Provides +1 Food, increasing by an additional +1 Food for every adjacent Mountain tile. Like Farms, receives an additional +1 Food if adjacent to freshwater at Civil Service, otherwise receiving this bonus at Fertilizer if not adjacent to freshwater.\nUnit: Slinger - Replaces the Archer. 5 Melee Strength (from 4, vs. 5). The Slinger has a chance to withdraw from melee combat initiated by foes, avoiding some damage depending on the available Movement of the attacker and the amount of available tiles behind the Slinger.\nBias: Hill"
, "India - Gandhi\nAbility: Population Growth (unchanged) - Settling Cities produces twice as much Unhappiness. Unhappiness generated from the number of Citizens in the empire is halved. (Cities provide an additional +3 Unhappiness.)\nBuilding: Mughal Fort - Replaces the Castle. In addition to the typical defensive perks, provides +4 Culture (from 2), and +2 Happiness. +2 Tourism at Flight. No longer requires Walls to construct.\nUnit: War Elephant - Replaces the Chariot Archer. 8 Melee Strength (from 9, vs. 6) and 11 Ranged Strength (vs. 10). Slightly slower (3 Movement vs. 4) and more costly to produce (46 hammers vs. 37). Does not receive Movement penalties in Rough terrain and does not require Horses to construct. Arrives with Swift Charge (+50% bonus against Melee foes; +25% against Gunpowder foes).\nBias: Grassland"
, "Indonesia - Gajah Mada\nAbility: Spice Islanders (unchanged) - Receive 2 copies of unique Luxury Resources in the first 3 Cities founded on separate landmasses. These Cities may never be Razed. (Each City must have its own unique landmass to receive a Luxury.) (Note that the unique Luxuries spawn as resource tiles beneath these Cities; if the City is settled atop an existing resource, the new Luxury will overwrite it.)\nBuilding: Candi - Replaces the Garden. In addition to the typical perks, provides +2 Faith and an additional +2 Faith for each Religion with at least 1 Follower in the City. Unlike the Garden, the Candi may be built without access to freshwater. 25% less costly to construct (60 hammers vs. 80).\nUnit: Kris Swordsman - Replaces Swordsmen. 15 Strength (from 14, vs. 14). After its first combat, this Unit receives one of many unique promotions at random: Invulnerability: +30% bonus when foe initiates combat. Restore +20 additional HP while fortified. Sneak Attack: Flanking bonus increases to +15% per ally (vs. +10%). Heroism: Radiates a +15% Combat Bonus to allies within 2 tiles as if it were a Great General. Ambition: +50% bonus when initiating combat, but a -20% penalty when defending. Restlessness: +1 Movement; Unit may attack twice. Recruitment: Heal 50 HP from non-Barbarian kills. (Harmful promotions Enemy Blade and Evil Spirits have been removed.)\nBias: Coast"
, "Ireland - Michael Collins\nAbility: Gaelic Revival - +2 Happiness from all National Wonders (excluding the Palace). All Cities receive a +15% Production bonus towards buildings required for National Wonders.\nUnit: Fenian - Replaces Riflemen. Significantly stronger (40 Strength vs. 34) and significantly cheaper to construct (110 hammers vs. 150).\nBuilding: Irish Pub - Replaces the Zoo. In addition to the typical perks, provides +3 Food in the City and requires no Gold maintenance. +1 Production from Wine, Tea, Coffee and Tobacco resources in the City.\nBias: None"
, "Iroquois - Hiawatha\nAbility: The Great Warpath (unchanged) - Units move through Forests and Jungles in friendly territory as if they were Roads. Forests and Jungles can be used to establish a City Connection upon the discovery of the Wheel, and extend the range of friendly Caravans like Roads.\nBuilding: Longhouse - Replaces the Workshop. In addition to the typical perks, the Longhouse provides +1 Production to all worked Forest and Jungle tiles in the City. Significantly cheaper to construct (50 hammers from 66, vs. 80). The Longhouse now retains the +10% Production bonus of the Workshop.\nUnit: Mohawk Warrior - Replaces Swordsmen. 15 Strength (from 14, vs. 14). Receives a +33% Combat Bonus fighting in Forests and Jungles. Does not require Iron.\nBias: Forest"
, "Israel - David\nAbility: Promised Land - +1 Culture from Pastures.\nUnit: Maccabee - Replaces Swordsmen. Earn 100% of foe’s Strength as Faith from kills. Significantly cheaper to construct (40 hammers vs. 50). Does not require Iron to construct.\nBuilding: Yeshiva - Replaces the Temple. In addition to the typical perks, grants +1 Food and +1 Production in the City, but is more expensive to construct (80 hammers vs. 67).\nBias: None"
, "Italy - Vittorio Emanuele III\nAbility: Rinascimento - +1 Culture from Specialists. Receive 250 Golden Age points upon completion of a Policy Tree, and if already in a Golden Age, extends it by 3 turns.\nUnit: Pittore - Replaces the Great Artist. Golden Ages started by a Pittore last for 9 turns (vs. 6), scaling to 14 turns with Chichen Itza or Universal Suffrage, but will not increase further with both.\nBuilding: Basilica - Replaces the Museum. Available at Industrialization (instead of Archeology). +20% faster Great Person generation in the City. Houses 2 slots for Great Artist Specialists, and generates 2 Great Artist Points each turn.\nBias: None"
, "Japan - Oda Nobunaga\nAbility: Bushido (unchanged) - Units fight at full Strength even when injured. +1 Culture from all Fishing Boats and +2 Culture from Atolls.\nBuilding: Dojo - Replaces the Barracks. In addition to the typical perks, provides +2 Science in the City and grants Units trained in this City an unconditional +10% Combat Bonus.\nUnit: Samurai (unchanged) - Replaces Longswordsmen. Arrives with Shock I (+15% bonus in Open terrain) and Great Generals II (this Unit will boost progress towards Great Generals through combat more than normal). While embarked, the Samurai may construct Fishing Boats in 4 turns.\nBias: Coast"
, "Jerusalem - Fulk V\nAbility: Holy Land - +1 Faith from Luxury Resources.\nUnit: Crusader - Replaces Longswordsmen. Available at Theology (instead of Steel). Much weaker (17 Strength vs. 21), but receives a +20% Combat Bonus in foreign territory and may enter rival territory without Open Borders. Earns Faith from kills equal to twice the Strength of defeated foes. Cheaper to construct (70 hammers vs. 80).\nBuilding: Outremer - Replaces the Courthouse. In addition to the typical perks, provides +2 Culture, Faith and Happiness in the City. Requires no Gold maintenance.\nBias: None"
, "Khmer - Suryavarman II\nAbility: Grand Baray of Angkor - Receive a free Baray in the Capital.\nBuilding: Baray - Replaces the Garden. In addition to the typical perks, 10% of Food is carried over after a Citizen is born. +2 Food and +2 Faith at Drama and Poetry. The Baray may be built without access to freshwater.\nUnit: Ballista Elephant - Replaces the Trebuchet, available at Machinery (instead of Physics). 18 Ranged Strength (vs. 14), 20 Melee (vs. 12), and 3 Movement (vs. 2). Gains a +100% bonus initiating combat with Cities (vs. +200%). Unlike the Trebuchet, the Ballista Elephant does not receive a Sight penalty. Receives the Feared Elephant (enemy Units adjacent to this Unit receive a -10% combat penalty) promotion. (Feared Elephant will not stack.) Slightly more costly to construct (90 hammers vs. 80).\nBias: None"
, "Kilwa - Ali ibn al-Hassan Shirazi\nAbility: Merchant Economy - Gain +5% Growth (excess Food) in the City for each foreign Trade Route departing the City. +4 Gold from internal Trade Routes. (Extra Food is updated the turn after the Trade Route is established.)\nUnit: Dhow - Replaces the Caravel, available at Compass (instead of Astronomy). Costs less to produce (70 hammers vs. 80), but has 17 Strength (vs. 20). Arrives with the Boarding Party I (+15% Combat Bonus against Naval Units) promotion.\nBuilding: Coral Port - Replaces the Workshop. In addition to the typical perks, provides varying yields to certain Coastal resources: +2 Production from Coral +1 Culture from Fish, Pearls, and Crabs +2 Gold from Whales\nBias: Coast"
, "Kongo - Mvemba a Nzinga\nAbility: Heart of Africa - Borders naturally expand 33% faster.\nUnit: Ngao Mbeba - Replaces Swordsman. 15 Strength (vs. 14). May not initiate combat, but gains double Strength defending from Ranged attacks. Does not require Iron to produce.\nBuilding: Slave Market - Replaces Colosseum. Subtracts 1 Citizen in the City upon completion. Provides +4 Production and +5 Gold, with an additional +3 Production and +2 Gold at Industrialization. Does not provide Happiness and does not require Gold maintenance.\nBias: Forest"
, "Korea - Sejong\nAbility: Scholars of the Jade Hall - +1 (from +2) Science from Specialists, +2 Science from Great Person tile improvements, and +1 Science from the Palace.\nUnit: Hwach’a - Replaces the Trebuchet. Massive 26 Ranged Strength (vs. 14), but slightly less Melee Strength (11 vs. 12). Suffers no Sight penalty, but receives no bonus initiating combat with Cities. Receives the Indirect Fire promotion.\nUnit: Turtle Ship (unchanged) - Replaces the Caravel. Massive 36 Strength (vs. 20), but receives no Sight bonus, may not Withdraw from Melee attacks, and possesses 4 Movement (vs. 5). Cannot enter Ocean tiles.\nBias: Coast"
, "Lithuania - Vytautas\nAbility: Baltic Mythology - Great Prophets generated by or given to Lithuania are replaced with Krivises. Cannot found a Religion.\nUnit: Krivis - Replaces the Great Prophet. Incapable of spreading or founding a Religion, instead used to create Sacred Groves.\nImprovement: Sacred Grove - Provides +1 Food, Production, Culture, Science and Faith. Each yield increases by +1 upon the discovery of Philosophy, Theology, Acoustics, Archeology, Plastics, Computers, and the Internet (for a total of 8 of each yield).\nUnit: Pestininkas - Replaces the Pikeman. Identical combat capabilities, but is significantly cheaper to construct (40 Production vs. 60).\nBuilding: Grand Cathedral of Vilnius - Behaves like a Grand Temple but can be constructed without the presence of religion and may be built outside of a Holy City. Cheaper to construct (63 hammers vs. 84).\nBias: None"
, "Macedonia - Alexander\nAbility: Macedonian Discipline - Barracks and Armories provide +1 Food, Culture and Happiness in the City. Receive a free Hetairoi at Horseback Riding.\nGreat Person: Hetairoi - Replaces the Great General. Considered a Mounted Unit with 15 Combat Strength and 4 Movement with identical mechanics to Horsemen, and arrives with several promotions: Leadership: Grants the Great General bonus to Units within 2 tiles as a General would, Great Generals II: This Unit will earn progress towards Great Generals through combat significantly faster, Charge: +33% bonus vs. wounded foes, Heavy Charge: Enemy Units will retreat if they receive more damage than this Unit; this Unit deals +50% damage to defenders incapable of retreat. Can upgrade to a Knight, but will lose its ability to create Citadels. Requires a Horse resource. (If no Horses are available when this unit is generated, it receives a Strategic Resource penalty!)\nUnit: Sarissophoroi - Replaces Pikemen. Available at Philosophy (instead of Civil Service). Weaker, (14 Strength vs. 16), but gains a +100% Combat Bonus (vs. +50%) against Mounted units.\nBias: None"
, "Madagascar (Malagasy) - Ralambo\nAbility: Sacred Hills of Imerina - +6 Culture and Faith from Holy Sites.\nUnit: Mpiambina - Replaces the Inquisitor. Ranged Unit with 8 Melee Strength, 14 Ranged Strength, 1 Range, and 3 Movement. Receives one promotion from a unique pool after its first round of combat: Kelimazala - Allows Unit to attack twice. Ramahavaly - +50% defensive bonus, -50% attacking penalty. Manjakatsiroa - +25% Combat Bonus in friendly territory. Rafantaka - Adjacent allies heal +15 HP while Fortified. This Unit heals every turn, even if an action was performed. Mosasa - +4 Sight, +4 Range. Rabehaza - Gain a chance to capture defeated enemies. Ambohimanambola - Grant the Great General bonus to nearby allies. Sehatra - Heal fully from every kill. Lambamena - +100% bonus initiating combat with Cities. Famadiahona - Knock back foes that take more damage than this Unit receives during combat. This unit gains a chance to Withdraw from Melee combat. Razana - +3 Movement. Great Generals that start their turn on the same tile as this Unit receive +2 Movement. Masina - +75% bonus against wounded foes.\nBuilding: Rova - Replaces Walls. In addition to the typical perks, provides +1 Happiness and +3 Faith.\nBias: None"
, "Manchuria - Nurhaci\nAbility: Eight Banners - Mounted, Armored, and Bomber Units receive the Volley promotion (+50% bonus vs. Fortified Units and Cities) and pay no Gold maintenance. Stables are built twice as fast and provide +1 Gold.\nBuilding: Canton Factory - Replaces the Bank. In addition to the typical perks, boosts City gold output by an additional +10% (+35% vs. 25%), may house an additional Great Merchant Specialist, and is half as costly to produce (67 hammers vs. 134).\nUnit: Qianlong Cavalry - Replaces Cavalry. Stronger and faster (36 Strength vs. 34 and 5 Movement vs. 4) and arrives with Great Generals I (this Unit will boost progress towards Great Generals through combat more than normal).\nBias: None"
, "Maori - Te Rauparaha\nAbility: Mana of Tumatauenga - During the first 5 turns, all units (except Recon units) receive +2 Movement and +1 Sight. After this, units receive +2 Movement during the first turn they appear. (Captured units, such as Workers, will receive this bonus on their first available move.)\nUnit: Maori Warrior - 9 Strength (from 8, vs. 8). Possesses the Haka War Dance (enemy Units adjacent to this Unit receive a -10% combat penalty) promotion. (Haka War Dance will not stack. In Brave New World, this unit belonged to Polynesia.)\nImprovement: Pa - Available at Engineering. +2 Food and +1 Faith. May only be built on Hills without resources and cannot be constructed adjacent to one another. Gains an additional +1 Food at Civil Service and Fertilizer. Units stationed on a Pa receive a +40% defensive bonus.\nBias: None"
, "Maurya - Ashoka\nAbility: Inscriptions of the Dharma - All non-Air Units receive a -10% Combat Penalty when attacking and a +10% Combat Bonus when defending.\nUnit: Fast Worker - Replaces the Worker. Ignores terrain Movement penalties.\nBuilding: Pillar of Ashoka - Replaces the Monument. Half as costly to construct (13 hammers vs. 26) and requires no Gold maintenance. Available at Pottery (instead of immediate availability).\nBias: None"
, "Maya - Pacal\nAbility: The Long Count (unchanged) - After researching Theology, choose a Great Person at the end of each Mayan calendar cycle (every 394 in-game ‘years’). Each type of Great Person may only be chosen once. (Great People chosen through Long Count cycles will delay the generation of the next naturally earned Great Person.) (Long Count intervals are based on fixed intervals regardless of when Theology was researched. Currently, these intervals are (on Quick speed): Turns  22 / 28 / 35 / 42 / 48 / 57 / 67 / 77 / 88 / 102 / 122 / 152 )\nBuilding: Pyramid (unchanged) - Replaces the Shrine. In addition to the typical perks, provides an additional point of Faith (2 vs. 1) and +2 Science.\nUnit: Atlatist (unchanged) - Replaces the Archer. Available immediately with identical combat capabilities and slightly less costly to construct (24 hammers vs. 27)\nBias: None"
, "Mexico - Benito Juarez\nAbility: Encomienda System - Receive a free Worker near the Capital at Pottery. City-States that are afraid of Mexico gain +6 Influence per turn when Mexico can demand tribute from them, but does not. Reveal all City-States within a 10-tile radius of your starting location after the end of the first turn.\nUnit: Ranchero - Replaces Settler. Does not halt Growth to produce, but does not protect the City from starvation. Food does not contribute to its Production.\nBuilding: Hacienda - Replaces Windmill. +1 Production from Luxury resources, +1 Gold from Bonus resources (e.g. Wheat, Fish), and +1 Food from Strategic Resources (e.g. Horses, Iron). Does not require Gold maintenance.\nBias: None"
, "Mongolia - Genghis Khan\nAbility: Mongol Terror - Gain a +30% Combat Bonus in combat with City-States and their Units. Mounted and Armored Units receive +1 additional Movement. Upon the discovery of Chivalry, reveal an additional Horse resource tile within the borders of every current Mongol city; these Cities yield an additional +1 Food from all Horse resources. (These Horses will not spawn over existing resources or features (such as forests, mountains, or Natural Wonders), but may spawn on Hills if necessary.)\nGreat Person: Khan (unchanged) - Replaces the Great General. In addition to the typical traits, the Khan may move further (5 Movement vs. 4) and greatly improves the healing capabilities of adjacent Fortified Units by an additional +15 HP. (Note that this healing bonus will not apply to Units stationed on the same tile as the Khan.)\nUnit: Keshik -  Replaces the Knight. A Ranged Mounted Unit with 5 Movement (vs. 4), 17 Strength (from 15) and 17 Ranged Strength (from 16). May move after combat and receives no penalty in combat with Cities. Arrives trained with Great Generals I (this Unit will boost progress towards Great Generals through combat more than normal) and Quick Study (+50% XP earned through combat).\nBias: Plains"
, "Moors - Abd-ar-Rahman III\nAbility: Glory of Al-Andalus - All Cities gain a +30% Production bonus towards buildings (not including Wonders) during the Medieval Era, decreasing to +15% in the Renaissance Era. (This ability updates on each turn or when technology is gained through other means. Upon entering the Industrial Era, the production bonus ends.)\nUnit: Granadine Cavalry - Replaces the Lancer. A Ranged Mounted unit with identical Combat Strength to the Lancer in addition to 29 Ranged Strength and 2 Range. The Granadine Cavalry sees no bonuses against Mounted Units and may not move after initiating combat, but may attack Cities without penalty.\nBuilding: Alcazaba - Replaces the Castle. Retains defensive capabilities in addition to providing +3 Science and +10% Food in the City.\nBias: None"
, "Morocco - Ahmad al-Mansur\nAbility: Gateway to Africa - Receive +2 Culture (from +1) and an additional +4 Gold (from +3) for each external Trade Route sent by or to Morocco. Rivals receive an additional +2 Gold for sending Trade Routes to Morocco. Receive an additional +1 Gold and Culture for every new Era entered. (In the Ancient Era, Morocco will only receive +2 / +4; increasing to +3 / +5 in Classical, etc…)\nImprovement: Kasbah - Available at Chivalry. May only be built on Desert tiles (excluding Oases). Provides +2 (from +1) Food, +1 Production, and +1 Gold.\nUnits gain a +50% Combat Bonus defending this tile.\nUnit: Berber Cavalry - Replaces Cavalry. In addition to the typical traits, receives a +25% Combat Bonus inside friendly territory and a +50% bonus fighting in Desert, Floodplains, and Oases.\nBias: Desert"
, "sore - Hyder Ali\nAbility: Brahmin Elite - Specialists provide +1 Food and Production, but generate +50% more Unhappiness. (This Unhappiness penalty interacts additively instead of multiplicatively with other bonuses or penalties. Universal Suffrage, for example, which reduces Specialist Unhappiness by 50%, would cancel out this penalty.)\nUnit: Rocket Corps - Replaces Artillery. Increased Melee Strength (23 vs. 21). Unlike Artillery, the Rocket Corps may attack without prior setup.\nBuilding: Mysore Palace - Replaces the Hermitage. Available at Chivalry (instead of Architecture). Requires Walls to be built in all Cities. In addition to the typical perks, provides +3 Production, Science and Gold. Upon completion, the empire enters a Golden Age.\nBias: Hill"
, "Nabataea - Aretas III\nAbility: Spring of Moses - Freshwater Farms receive +1 Food at Mathematics rather than Civil Service.\nUnit: Zabonah - Replaces the Scout. May not attack. 3 Movement (vs. 2). May discover Cities from an additional +3 tiles away. When this Unit discovers a Capital or City-State, gain +10 Gold for the Empire. Will not upgrade from Ruins. (The Zabonah must make Sight contact with players and City-States to ‘meet’ them and will not ‘meet’ when discovering Cities only due to its expanded range.)\nBuilding: Rock-Cut Tomb - Replaces the Caravansary. In addition to the typical perks, provides an additional +1 Gold (3 vs. 2) and +1 Food in the City. Gains an additional +1 Food for each Trade Route departing the City.\nBias: Desert"
, "Netherlands - William\nAbility: Dutch East India Company - +1 Happiness from each unique Luxury in the empire and +1 Gold from Luxury resource tiles.\nImprovement: Polder - Available at Guilds. May be built on Marsh and Floodplain tiles and on Lakes or Coastal tiles with at least 3 adjacent land tiles. +3 Food if constructed on Marsh, +2 Food if constructed on Lakes or Coast. Gains +1 Production and +2 Gold at Economics.\nUnit: Sea Beggar - Replaces the Privateer. 27 Strength (from 25, vs. 27). Arrives with the Supply (may heal outside friendly territory; heals 15 HP each turn), Coastal Raider (+20% bonus when attacking Cities; Steal Gold equal to 33% of inflicted damage) and Boarding Party I (+15% bonus in Melee combat with Naval Units) promotions.\nBias: Coast; near Wetlands (Marsh and Floodplains) (previously Grassland)."
, "New Zealand - Michael Joseph Savage\nAbility: Where She Goes - Earn 10 Faith, 6 Culture, 40 Gold, or 12 Science when meeting a Civilization or City-State for the first time. (This bonus is randomly chosen.)\nUnit: Defender - Replaces the Ironclad. 50 Strength (vs. 45). Earns a +15% bonus inside friendly territory and ignores Zone of Control movement penalties when within 2 tiles of a friendly City. In addition to the typical traits, arrives with Cover I (gain a +33% bonus defending against Ranged attacks). Doesn’t require Coal.\nUnit: Maori Battalion - Replaces Infantry. Possesses the promotions and traits\nof a Marine. Receive a Combat Bonus the further this unit is away from the Capital (+2% per tile to a maximum of +40%). Each Battalion stationed within a City-State’s borders earns +1 Influence with that City-State each turn.\nBias: Coast"
, "Normandy - William the Conqueror\nAbility: Castle Builders - Units gain a +10% Combat Bonus outside of friendly territory. Cities receive +5 additional Strength.\nImprovement: Motte and Bailey - Available at Engineering. +1 Food and Production. +2 Culture at Flight. Cannot be built adjacent to one another. Units gain a +25% Combat Bonus defending this tile.\nUnit: Pedite - Replaces the Longswordsman. Available at Metal Casting (instead of Steel). 20 Strength (vs. 21). Marginally cheaper to produce (77 hammers vs. 80). Arrives with Shock I (+15% bonus vs. foes in Open terrain) and may construct Motte and Baileys.\nBias: None"
, "Norway - Harald Hardrada\nAbility: Nordic Bounty - +1 Faith from Coastal resources. +2 Food and +1 Production from Snow tiles.\nUnit: Ski Infantry - Replaces Great War Infantry (previously Riflemen). Matches the strength of its counterpart and arrives with Drill I and II (total of +30% bonus fighting in Rough terrain) and the unique Ski Infantry promotion (+25% bonus fighting in Snow, Tundra and Hills without Forests or Jungles; move twice as far through these tiles). (In Brave New World, this unit belonged to Denmark.)\nBuilding: Stave Church - Replaces the Temple. +1 Production from Tundra and Snow tiles. Cheaper to construct (50 hammers vs. 67) and requires no Gold maintenance.\nBias: Coast"
, "Nubia - Amanitore\nAbility: Ta Seti - Begin with a free Apedemak’s Bow.\nUnit: Apedemak’s Bow - Replaces the Scout and has identical Strength, but is classified as a Ranged unit and may attack with 3 Range. Will not upgrade from Ruins, but can upgrade with Gold like the Scout when appropriate.\nBuilding: Blast Furnace - Replaces the Forge. In addition to the typical perks, provides +2 Culture by default, +2 Culture from Iron resources, and newly-trained Ranged, Siege and Recon units receive the Accuracy I (+15% bonus in Open terrain) promotion for free. Does not require resources nearby and does not require Gold maintenance.\nBias: Desert"
, "Oman - Saif bin Sultan\nAbility: Chain of the Earth - All Naval Units ignore Zone of Control movement penalties. Receive a free Seaport in conquered Cities.\nUnit: Baghlah - Replaces the Galley. Greater Melee Strength (8 Strength vs. 6) and Ranged Strength (12 vs. 8). Moves further (4 Movement vs. 3) and receives Faith and Gold from kills equal to the Strength of the defeated foe. Arrives with the Coastal Raider I (+20% bonus initiating combat with Cities; steal Gold equal to 33% of inflicted damage) promotion.\nBuilding: Minaa’ - Replaces the Harbor. Enemy Naval Units take 30 damage if they end their turn next to this City. Provides +5 City Strength, and +2 Production for each Trade Route departing the City. Allows units to Airlift between Cities with Minaa’s.\nBias: Coast"
, "Ottomans - Suleiman\nAbility: Millets - Each City gains +1 Local Happiness for each Religion present in the City. Receive Faith when promoting Units equal to the required experience (not when insta-healing).\nUnit: Sipahi - Replaces the Lancer. In addition to the typical traits, receives +1 Sight and Movement (5 vs. 4) and may Pillage without movement penalty.  Available at Gunpowder (previously Metallurgy) and costs less to produce (99 hammers from 123, vs. 123).\nUnit: Janissary - Replaces Musketmen. Gains a +25% bonus when initiating combat and heals 50 HP from kills. Less costly to produce (80 from 100, vs. 100).\nBias: None (previously Coast)"
, "Palmyra - Zenobia (new! v31)\nAbility: Pearl of the Desert - Cities provide fresh water to all adjacent tiles. Gardens and Water Mills ignore terrain requirements.\nBuilding: Palmyrene Theater - Replaces Amphitheaters. Provides +2 Gold. +1 Production, Gold, and Culture from Oases, +1 Production from Lake tiles. Doesn’t require Gold maintenance.\nUnit: Clibanarius - Replaces Horsemen. 14 Strength (vs. 12), arrives with Heavy Charge (enemy Units will retreat if they receive more damage than this Unit; this Unit deals +50% damage to defenders incapable of retreat). This promotion is kept on upgrade.\nBias: Desert"
, "Papal States (Vatican) - Urban II\nAbility: The Holy See - +1 Food, Production, Science, Gold, Culture and Faith from all Holy Sites. Receive 2 free Delegates in the World Congress.\nUnit: Swiss Guard - Replaces Landsknecht. Does not require the Mercenary Army policy, but still must be purchased. Available at Economics. More expensive to purchase (210 Gold vs. 160), but is faster (3 Movement vs. 2) and significantly stronger (25 Strength vs. 16). Receives Faith and Gold from kills equal to the Strength of the defeated foe, and arrives with Medic I and II (adjacent allies heal a total of +10 additional HP while Fortified). May upgrade into Riflemen.\nBuilding: Saint Peter’s Basilica - Replaces the Grand Temple. In addition to the typical perks, provides a free Cathedral in the City and spawns a Great Prophet near the City.\nBias: None"
, "Persia - Darius I\nAbility: Achaemenid Legacy - Golden Ages last +50% longer. During a Golden Age, Units receive +1 Movement. No longer receives a +10% Combat Bonus during a Golden Age.\nBuilding: Satrap’s Court (unchanged) - Replaces the Bank. In addition to the typical perks, provides an additional +1 Gold (3 vs. 2) and +2 Happiness.\nUnit: Immortal (unchanged) - Replaces Spearmen. 12 Strength (vs. 11). In addition to the typical traits, the Immortal heals an additional +10 HP while fortified.\nBias: None"
, "Philippines - Emilio Aguinaldo\nAbility: The Good Fight - Filipino Civilian and Naval Units receive +2 Movement in your own territory. The first two Cities you settle (after your Capital) begin with +1 extra Citizen.\nUnit: Gerilya - Replaces Expeditionary Forces. Boasts a whopping 55 Strength (vs. 40). In addition to the Force’s innate promotions, the Gerilya arrives with Volley (gain a +50% bonus against Fortified Units and Cities), 3 Movement (vs. 2), +3 additional Movement while embarked, and +1 Sight while embarked.\nBuilding: National Church - Replaces the Zoo, but available at Compass instead of Printing Press. In addition to the typical perks of a Zoo, the National Church provides +1 Culture and +4 Faith, and provides +15 XP to Units trained in the City. Less costly to construct (100 hammers vs. 120).\nBias: Coast"
, "Phoenicia - Hiram\nAbility: Skillful Traders - Receive a Square Sail Ship at Sailing. Upon the discovery of Optics, newly settled Cities begin with +1 extra Citizen.\nUnit: Square Sail Ship - Replaces the Trireme. Can see 1 tile further than its counterpart and receives the Supply (may heal outside friendly territory; heals 15 HP each turn) promotion. Slightly cheaper to train (25 hammers vs. 30).\nBuilding: Trade Harbor - Replaces the Harbor. In addition to the typical perks, provides +15% production towards Naval units and +1 Production from all Coastal resources.\nBias: Coast"
, "Poland - Casimir III\nAbility: Solidarity - Social Policies require -10% less Culture to adopt.\nBuilding: Ducal Stable - Replaces the Stable. In addition to the typical perks, provides +1 Gold from each Horse, Sheep, Cattle and Maize resource in the City. +15 XP for Mounted Units trained in the City. Requires no Gold maintenance.\nUnit: Winged Hussar - Replaces the Lancer. 28 Strength (vs. 25) and 5 Movement (vs. 4). In addition to the Lancer’s innate promotions, arrives with the Heavy Charge (enemy Units will retreat if they receive more damage than this Unit; this Unit deals +50% damage to defenders incapable of retreat) promotion. No longer arrives with Shock (+15% bonus vs. foes in Open terrain).\nBias: Plains"
, "Polynesia - Kamehameha\nAbility: Wayfinding - Units may embark and move through Oceans immediately. Embarked Units gain +1 Movement, +2 Sight (from +1), and double defensive Strength. Units gain a +10% Combat Bonus fighting within 2 tiles of a Moai.\nImprovement: Moai (unchanged) - Available at Construction. Must be built on land adjacent to the coast. Provides +1 Culture and gains an additional +1 Culture for each adjacent Moai. Gains +1 Gold at Flight.\nUnit: Koa - Replaces Longswordsmen. 23 Strength (vs. 21), requires no Iron resources, and arrives with the Amphibious (attack from the sea or over rivers without penalty) promotion. Obsolete at Rifling (instead of Gunpowder).\nBias: Coast"
, "Portugal - Maria I\nAbility: Mare Clausum - Receive twice as much Gold from Resource Diversity from Trade Routes. Caravans and Cargo Ships are 33% less costly to construct.\nBuilding: Feitoria - Replaces the Harbor. In addition to the typical perks, provides +1 Gold from Coastal resources. Naval units trained in this City receive +15 XP. Cheaper to construct (67 hammers vs. 80) and doesn’t require Gold maintenance.\nUnit: Nau (unchanged) - Replaces the Caravel. 6 Movement (vs. 5). In addition to the typical perks, the Nau may perform a unique action when adjacent to foreign territory, gaining Gold for the empire and XP for the Unit scaling with the distance from Portugal’s Capital.\nBias: Coast"
, "Prussia - Frederick\nAbility: Army with a State - All Land Units may receive unique Promotions upon leveling up. +50% Food and Production from internal Trade Routes.\nBuilding: Fabrik - Replaces the Factory. 25% cheaper to produce (180 hammers vs. 240) and does not require Coal resources.\nUnit: Landwehr - Replaces Riflemen. Available at Military Science instead of Rifling. Arrives trained with Blitz (may attack twice each turn) and Quick Study (+50% Experience earned through combat). 3 Movement (vs. 2).\nUnique Promotions: Tier 0 - Gehorsam: Designates Units capable of learning further Promotions. Tier 1 - Disziplin: +10% Combat Strength. Tier 2 - Fleiss: +25% bonus attacking, or Tapferkeit: +25% bonus defending. Tier 3 - Zielstrebigkeit: +1 Extra Attack (requires Fleiss), Härte: +50% Defensive Strength vs. Ranged Units (requires Tapferkeit), or Pünktlichkeit: +1 Movement (requires either). (Zielstrebigkeit cannot be chosen by Paradropping Units.) Tier 4 - Zuverlässigkeit: Gain a bonus when near Great Generals and Heal every turn (requires Zielstrebigkeit), Zurückhaltung: +30% bonus in friendly territory (requires Härte), or Pflichtbewusstsein: +50% bonus vs. Mounted and Armored Units in addition to +1 Movement (requires Pünktlichkeit).\nBias: None"
, "Romania - Carol I\nAbility: Nihil Sine Deo - Units gain a +10% Combat Bonus against wounded foes. +25% Culture output during Golden Ages (for a total of +45% Culture).\nUnit: Vanator - Replaces the Gatling Gun. 31 Melee and Ranged Strength (vs. 30) and 2 Range (vs. 1).\nBuilding: Painted Monastery - Replaces the Garden. In addition to the typical perks, provides +1 Production, +2 Faith, and +1 Great Artist point per turn. Does not require freshwater. Cheaper to construct (67 vs. 80 hammers).\nBias: None"
, "Rome - Augustus Caesar\nAbility: Glory of Rome (unchanged) - Gain +25% Production towards any Buildings that already exist in the Capital.\nUnit: Ballista - Replaces the Catapult. 8 Melee Strength (vs. 7) and 10 Ranged Strength (vs. 8). May attack without prior setup. Receives the Indirect Fire promotion.\nUnit: Legion - Replaces Swordsmen. 16 Strength (from 17, vs. 14). May construct Roads and Forts.\nBias: None"
, "Russia - Catherine\nAbility: Siberian Riches (unchanged) - +1 Production from all Strategic Resources (e.g. Horses, Iron, etc.). Horse, Iron, and Uranium tiles provide twice the resources.\nBuilding: Krepost (unchanged) - Replaces Barracks. In addition to the typical perks, reduces the Culture and Gold costs of acquiring tiles in the City by -25%.\nUnit: Cossack - Replaces Cavalry. In addition to the typical traits, gains a +25% bonus (from +33%) in combat with wounded foes.\nBias: Tundra"
, "Scotland - Robert the Bruce\nAbility: Flower of Scotland - +2 Production, Science and Culture from Writer's, Artist's and Musician's Guilds. +33% faster Great Person generation in the Capital.\nUnit: Gallowglass - Replaces Riflemen. Cheaper to construct (120 hammers vs. 150) and available at Metallurgy (instead of Rifling). 32 Strength (vs. 35). Arrives with Altitude Training (+10% bonus fighting in Hills; move twice as fast through these tiles) and Volley (+50% bonus vs. Fortified Units and Cities). Unlike Riflemen, requires 1 Iron resource to train.\nBuilding: Ceilidh Hall (unchanged) - Replaces the Opera House. In addition to the typical perks, provides an additional +1 Culture and +3 Happiness in the City. (In Brave New World, this building belonged to the Celts.)\nBias: Hill"
, "Shoshone - Pocatello\nAbility: Great Expanse - Founded Cities start with 4 additional tiles (previously 8) claimed. Units gain a +15% Combat Bonus in their own territory.\nUnit: Pathfinder - Replaces the Scout. 27 hammers to produce (from 30, vs. 16). 8 Strength (vs. 5). When entering Ancient Ruins, the Pathfinder may select the benefit from the available pool. (This Unit upgrades into a Composite Bowman (instead of an Archer) from Ruins.)\nUnit: Comanche Riders (unchanged) - Replaces Cavalry. 5 Movement (vs. 4) and costs less to produce (132 hammers vs. 150).\nBias: None"
, "Siam - Ramkhamhaeng\nAbility: Father Governs Children (unchanged) - Gain +50% more Food, Culture Faith and Happiness from friendly City-States. Units from Military City-States arrive with an additional +10 XP and arrive +50% faster.\nBuilding: Wat (unchanged) - Replaces the University. In addition to the typical perks, provides +3 Culture.\nUnit: Naresuan’s Elephant (unchanged) - Replaces the Knight. 25 Strength (vs. 20), but 3 Movement (vs. 4). Gains a +50% bonus against Mounted Units and does not require Horses to construct.\nBias: River"
, "Sioux- Sitting Bull\nAbility: Dwellers of the Plains - Units receive a +15% Combat Bonus fighting in Plains.\nUnit: Buffalo Hunter - Replaces Composite Bowman. 12 Ranged Strength (vs. 11), 8 Melee (vs. 7). Capable of constructing Tipis.\nImprovement: Tipi - Available at Trapping. May only be constructed on flat Plains or flatland Deer / Bison resources and must be adjacent to a Luxury resource. Provides +1 Food, +1 Faith. Bonus +1 Culture if adjacent to a city and +1 Gold if adjacent to a River. Gains +1 Food at Civil Service and +1 Faith at Theology.\nBias: Plains"
, "Songhai - Askia\nAbility: River Warlord - Receive triple Gold from clearing Barbarian camps and capturing Cities. Land Units receive the Amphibious (attack from the sea or over rivers without penalty) promotion and ignore terrain costs moving along or across Rivers.\nBuilding: Mud Pyramid Mosque (unchanged) - Replaces the Temple. In addition to the typical perks, provides +2 Culture and requires no Gold maintenance.\nUnit: Mandekalu Cavalry (unchanged) - Replaces the Knight. Receives no penalty in combat with Cities and is slightly cheaper to produce (74 hammers vs. 80).\nBias: River"
, "Spain - Isabella\nAbility: Seven Cities of Gold - Gain 100 Gold (previously 500 if first to discover and 100 otherwise) and +1 additional Happiness for the empire upon the discovery of a Natural Wonder. Tile yields (including Happiness yields) from Natural Wonders are doubled.\nBuilding: Plaza de Toros - Replaces the Circus. In addition to the typical perks, provides +2 Culture, and may also be built with an improved source of Cattle in addition to Horses and Ivory.\nUnit: Tercio (unchanged) - Replaces the Musketman. 26 Strength (vs. 24) and gains a +50% bonus against Mounted Units, but is slightly more expensive to construct (107 hammers vs. 100).  (This unit is classified as a Melee Unit and not a Gunpowder Unit.)\nBias: Coast"
, "Sumeria - Gilgamesh\nAbility: Cradle of Civilization - +2 Culture from every City upon the discovery of Drama and Poetry.\nBuilding: Ziggurat - Replaces Temple. In addition to the Faith yield, provides +10% Science. Only costs 1 Gold to maintain (vs. 2).\nUnit: Phalanx - Replaces Spearman. Available at Mining. +50% more effective at flanking (+15% per adjacent ally vs. +10%) and cheaper to construct (30 hammers vs. 37).\nBias: None"
, "Sweden - Gustavus Adolphus\nAbility: Nobel Prize - +20% faster Great Person generation in all Cities. Receive 100 Influence and 200 Gold when gifting a Great Person to a City-State.\nUnit: Carolean - Replaces Musketmen (instead of Riflemen). 3 Movement (vs. 2). Identical strength; arrives with March (heal 10 HP each turn even if an action was performed).\nBuilding: Falu Gruva - Replaces Ironworks. Available at Metal Casting (instead of Machinery). In addition to the typical perks, provides +1 Production to all Hill tiles in the City. Provides +6 Tourism at Flight.\nBias: Tundra"
, "Switzerland - Jonas Furrer (new! v31)\nAbility: Swiss Banks - Cities with an active Merchant Specialist provide +2 Production, Gold, and Science.\nBuilding: Ski Resort - Replaces Stadiums. Available at Electricity (instead of Refrigeration). Provides +3 Happiness (vs. 2), +3 Culture, and +5 Tourism. Provides an additional +5 Tourism and +2 Gold for every Mountain within 3 tiles of the City; this bonus will only stack 5 times. Half as costly to construct (165 hammers vs. 330) and doesn’t require Gold maintenance. Doesn’t require a Zoo to construct.\nBuilding: Reisläufer Post - Replaces Armories. Trained units receive the Mountaineer promotion (+10% Strength and +1 Movement at the start of turn when adjacent to Mountain tiles). Doesn’t require Gold maintenance. Spawns a Reisläufer upon completion.\nUnit: Reisläufer - A unique Unit only available by completing Reisläufer Posts. Comparable to Longswordsmen with 20 Strength and 3 Movement. Receives Gold from defeated foes equal to twice their Strength.\nBias: Hills"
, "Tibet - Ngawang Lobsang Gyatso\nAbility: Eightfold Path to Nirvana - Receive +2 Food, Production, Gold, Culture, Faith and Science in the Capital upon the discovery of Drama and Poetry. +1 to those yields at Education, Acoustics, Industrialization, Radio, Radar and Globalization.\nUnit: Dalai Lama - Replaces Great Prophets generated and received by Tibet. No vision penalty and may spread Religion 1 extra time. May also start 7-turn Golden Ages (consuming the unit).\nImprovement: Monastery - Available at Calendar. Can only be built on Hills. Provides +2 Faith and +1 Culture; +1 additional Faith at Theology. +1 Culture for each adjacent Mountain. May be built in Forests and Jungles without removing them.\nBias: None"
, "Timurids - Timur\nAbility: Ulugh Beg’s Observatory - +5 City Strength and +15% Science, Gold and Culture in the original Capital. These bonuses are terminated if the original Capital is captured.\nUnit: Marathi Rider - Medieval Air Unit available at Chivalry. Replaces Horsemen. Requires 1 Horse; has 5 Range and 19 Combat Strength. Behaves as an Air Unit, and receives the appropriate promotions.\nBuilding: Serai - Replaces Caravansary. Instead of providing +2 Gold at base, provides +1 Gold for every 3 Citizens in the City and otherwise retains the typical perks. Allows units to Airlift between Cities with Serais and increases Air Unit capacity in the City by 1. More costly to construct (67 hammers vs. 60). (This bonus scales linearly. In practice, each Citizen provides +0.33 Gold.)\nBias: None"
, "Tonga - 'Aho'eitu\nAbility: The Friendly Islands - Resting Influence with City-States is increased by 5. All Islands, Coast tiles, and Coast-adjacent land tiles within a 10-tile radius of your starting Settler are revealed immediately.\nUnit: Matato’a - Replaces the Archer (but does not require Archery to construct). 3 Movement (vs. 2) and +1 Sight; these bonuses are lost with upgrades. Cheaper to construct (20 hammers vs. 26). Obsolete at Machinery. Cannot upgrade from Ruins.\nBuilding: Mala’e - Replaces the Granary. Available at Sailing. Provides +1 Faith. Provides +2 Food and Culture if the city is adjacent to at least 3 Coastal tiles.\nBias: Coast"
, "Turkey - Ataturk\nAbility: Westernization - Amphitheaters, Opera Houses, Museums and Broadcast Towers are built +50% faster and each provide +1 Science and Production. +1 Production and Science from Great Works.\nUnit: Kuva-yi Milliye - Replaces Great War Infantry. Weaker (47 Strength vs. 50), but boasts 3 Movement (vs. 2). Gains a +50% Combat Bonus when initiating combat, and may upgrade to Infantry for only 10 Gold.\nBuilding: Halkevleri - Replaces the Public School. In addition to typical perks, provides +3 Culture and is 20% cheaper to construct (160 hammers vs. 200).\nBias: None"
, "United Arab Emirates (UAE) - Sheikh Zayed\nAbility: Yallah Habibi - Upon completing a World Wonder, receive 100 Gold and start a We Love The King Day in the City where it is built. All Units gain +3 Gold per turn and +1 Experience each turn on tiles with a Trade Route. (This King Day lasts for 15 turns and will stack with existing King Days.) (Gold and XP bonus is provided on each and every tile connecting the Trade Route.)\nBuilding: Burj - Replaces the Hotel. Compared to the Hotel, the Burj provides +2 Gold and Culture to Great Person Improvements and Desert tiles in the City (with the exception of Floodplains).\nUnit: Qasimi Raider - Replaces the Privateer. Earns twice as much Gold from pillaging Trade Routes and attacking Cities. 8 Movement (vs. 6), and 20% cheaper to construct (80 hammers vs. 100).\nBias: Coast"
, "Ukraine - Yaroslav I\nAbility: Chumatskyi Shliah - +1 Food from Maize, Wheat and Salt resources after researching The Wheel. City Connections provide +2 Gold to connected Cities. (The Capital also receives +2 Gold after the first Connection is made.)\nUnit: Tachanka - Replaces the Gatling Gun. Classified as a Mounted Ranged unit with 2 Range and 4 Movement and suffers the same Movement and Defensive Penalties as all Mounted Units.\nBuilding: Knyaz Court - Replaces the Market. Compared to the Market, provides an additional point of Gold at base (2 vs. 1). Each Knyaz Court in the empire generates 20 Gold whenever Ukraine consumes a Great Person.\nBias: None"
, "Venice - Enrico Dandolo\nAbility: Serenissima - Receive a free Trade Route and Cargo Ship in the Capital once Compass is researched. Cargo Ships may not be plundered. Capable of producing Settlers.\nUnit: Great Galleass (unchanged) - Replaces the Galleass. 18 Combat Strength (vs. 16) and 20 Ranged Strength (vs. 17), but costs 10% more to produce (73 hammers vs. 67).\nBuilding: Grand Canal of Venice - Replaces the East India Company. Compared to the East India Company, provides an additional free Trade Route for a total of an additional two; boosts Gold generation in the City by an additional +15%, and does not require Markets in every City to produce. Available at Currency instead of Guilds.\nBias: Coast"
, "Vietnam - Hai Ba Trung\nAbility: Tam Giaiào - +2 Food, +1 Production from Marsh. +1 Faith from Jungle. Units receive double Movement through Marsh and Jungle tiles and receive a Combat Bonus in Marshes (+30%) and Jungles (+15%).\nUnit: Viet Cong - Replaces Infantry. Moves further (3 Movement vs. 2). When initiating combat, performs a bonus Ranged Attack prior to Melee combat. Gains a +25% Combat Bonus against Gunpowder units. This Unit may traverse mountains, taking 50 HP damage if it ends its turn on one. Cheaper to construct (233 hammers vs. 280).\nBuilding: Vo Khi - Replaces the Armory, available at Metal Casting (instead of Steel). In addition to the typical perks, provides +1 Food, +1 Culture and +1 Production from Marsh tiles and +1 Culture from Jungle tiles. All Melee Units trained in this City receive the Woodsman promotion (units move twice as fast through Forest and Jungle tiles). Doesn’t require Barracks to construct.\nBias: Wetland (Marsh and Floodplains)"
, "Wales - Owain Glyndwr\nAbility: Hafod a Hendref - +1 Food and +1 Gold from Sheep at Animal Husbandry. Units receive a +10% Combat Bonus fighting in Hills.\nUnit: Saethwyr - Replaces Crossbowmen. 15 Combat Strength (vs. 13).\nImprovement: Caer - Available at Chivalry. +3 Gold, +1 Culture, and +1 Production. Units gain a +25% Combat Bonus defending this tile. +1 Culture at Acoustics. Receives bonus yields from certain policies: +1 Culture from Cultural Exchange, +1 Science from Free Thought, +1 Food from completing the Commerce tree. May only be built on Hills without resources.\nBias: Hill"
, "Yugoslavia - Aleksandar I (new! v31)\nAbility: Non-Aligned Doctrine - Pick a free Ideology Tenet when adopting or switching Ideologies and receive bonuses corresponding to both rival Ideologies. If not Freedom, Specialists provide +1 Gold. If not Autocracy, receive +15% Production towards land Units. If not Order, receive +2 Production and Science in all Cities.\nUnit: M-84 - Replaces Tanks. Ignores Zone of Control movement penalties. Uh oh.\nBuilding: Spomenik - Replaces Museums. In addition to the typical perks, provides +20% Science in the City, but costs more to construct (230 hammers vs. 200).\nBias: None"
, "Zimbabwe - Nyatsimba Mutota\nAbility: Great Zimbabwe - +25% Production towards buildings and military Units in the Capital. (Guilds and National and World Wonders do not count as buildings).\nUnit: Shona Warrior - Replaces the Warrior. 9 Strength (vs. 8) and is capable of building Quarries and Farms.\nBuilding: Stone Mason - Replaces Stoneworks. Does not provide Happiness, but provides +2 Culture at Masonry, and otherwise retains the typical perks. Doesn’t require any nearby resources to construct.\nBias: Hill"
, "Zulu - Shaka\nAbility: Iklwa (unchanged) - Melee Units pay 50% less Gold maintenance. All Units require 25% less experience to promote.\nBuilding: Ikanda (unchanged) - Replaces Barracks. Grants the Buffalo Horns promotion to all pre-Gunpowder Melee Units trained in the City and allows these Units to earn the Buffalo Chest and Loins promotions. Horns: +1 Movement, +25% Flanking Bonus, and +10% defensive Strength against Ranged attacks Chest: +10% Bonus in Open Terrain, an additional +25% Flanking Bonus, and an additional +10% defensive Strength against Ranged attacks (requires Horns) Loins: +10% Combat Strength, an additional +25% Flanking Bonus, and an additional +10% defensive Strength against Ranged attacks (requires Chest)\nUnit: Impi (unchanged) - Replaces Pikemen. When initiating combat, performs a bonus Ranged Attack prior to Melee combat. Gains +25% Combat Strength against Gunpowder units.\nBias: Avoid Jungle/"]
    
    self.ng_list = ["Stag - Eikthyrnir", "Goat - Heidrun", "Wolf - Fenrir", "Raven - Huginn and Muninn", "Bear - Bjarki", "Boar - Slidrugtanni", "Snake - Sváfnir", "Dragon - Nidhogg", "Horse - Svadilfari", "Kraken - Lyngbakr", "Ox - Himminbrjotir", "Lynx - Brundr and Kaelinn", "Squirrel - Ratatoskr", "Rat - Dodsvagr", "Eagle - Hræsvelg", "Lion - Neustria", "Stoat - Nominoe", "Hounds - Garm"]

    self.colors = [
    0xFF5733,  # Vibrant Orange
    0x33FF57,  # Bright Green
    0x3357FF,  # Deep Blue
    0xFF33F5,  # Pinkish Purple
    0x57FF33,  # Light Green
    0xF533FF,  # Magenta
    0x33FFF5,  # Cyan
    0xF5FF33,  # Yellow
    0x337FFF,  # Sky Blue
    0xFF3374,  # Rose Pink
    0x7F33FF,  # Violet
    0x33FF7F,  # Sea Green
    0xB833FF,  # Rich Lavender
    0xFF8C33,  # Burnt Orange
    0x33FFBB   # Turquoise
]



  def drafter(self, draft_list, num_players, num_choices=3):
    random_list = random.sample(draft_list, num_players*num_choices)
    chunk_size = len(random_list) // num_players
    return [random_list[i:i+chunk_size] for i in range(0, len(random_list), chunk_size)]

  

  def format_civ_embed(self, civ_detail, player_num, choice_num):
    embed = discord.Embed(title=f"Player {player_num} - Choice {choice_num}", color=self.colors[player_num-1])
    details = civ_detail.split('\n')
    embed.add_field(name="__**"+details[0]+"**__", value="", inline=False)       
    # Process each detail line, ensuring it doesn't exceed the character limit
    for detail in details[1:]:
        # Splitting the detail by the first colon
        split_detail = detail.split(':', 1)
        if len(split_detail) == 2:
            field_name, field_value = split_detail
            field_name = field_name.strip()
            field_value = field_value.strip()

            # Check if field_value exceeds the Discord limit
            if len(field_value) > 1024:
                # Truncate and add '...' to indicate truncation
                field_value = field_value[:1021] + '...'
            
            if(field_name == "Ability"):
              field_name = "🌟 Ability"
            elif(field_name == "Unit"):
              field_name = "🗡️ Unit"
            elif(field_name == "Building"):
              field_name = "🏛️ Building"
            elif(field_name == "Improvement"):
              field_name = "🧱 Improvement"
            elif(field_name == "Bias"):
              field_name = "🏞️ Bias"
            elif(field_name == "Unique Promotions"):
              field_name = "🏅 Unique Promotions"
            elif(field_name == "Great Person"):
              field_name = "👑 Great Person"
            elif(field_name == "Great Work"):
              field_name = "📜 Great Work"

            embed.add_field(name=field_name, value=field_value, inline=False)
        else:
            # Handle the case where ':' is not found in the detail
            # You can decide how to handle this case. For example:
            embed.add_field(name="Detail", value=detail, inline=False)
    return embed

  @app_commands.command(name="draft", description="test")
  @app_commands.choices(game=[app_commands.Choice(name="Civilization 5 (Lekmod)", value="civ"), app_commands.Choice(name="Armello", value="armello"), app_commands.Choice(name="Northgard", value="ng")])
  async def draft(self, interaction: discord.Interaction, game: app_commands.Choice[str], num_players: int, num_choices: int):
      await interaction.response.defer()
      if game.value == "civ":
          res = self.drafter(self.civ_list, num_players, num_choices)
      elif game.value == "armello":
          res = self.drafter(self.armello_list, num_players, num_choices)
      elif game.value == "ng":
          res = self.drafter(self.ng_list, num_players, num_choices)

      if game.value != "civ":
          embed = discord.Embed(title=f"{game.name} Draft", color=0x00ff00)  # You can change the color
          embed.add_field(name="Players", value=str(num_players), inline=True)
          embed.add_field(name="Choices", value=str(num_choices), inline=True)
          for i, item in enumerate(res, start=1):
              embed.add_field(name=f"Player {i}", value=' | '.join(item), inline=False)
          await interaction.followup.send(embed=embed)

      elif game.value == "civ":
          embed = discord.Embed(title=f"{game.name} Draft", color=0x000000)
          embed.add_field(name="Main Page", value="https://docs.google.com/document/d/18tsjg2C1wKA7I41GktDRr6R83eUrhn4FHi9EUEtpKvI", inline=False)
          embed.add_field(name="Civ Masterlist", value="https://docs.google.com/document/d/e/2PACX-1vSUkKuhdURg8zS2P4nMHRjXvkp-Tg5QPxvMfaXVoIiyfBgPQxqVaxAeJG9JfZN6HAq9SjYE4NLxjLyk/pub", inline=False)
          await interaction.followup.send(embed=embed)
          for i, civ_choices in enumerate(res, start=1):
            choice_num = 1
            for civ_detail in civ_choices:
              embed = self.format_civ_embed(civ_detail, i, choice_num)
              choice_num += 1
              await interaction.followup.send(embed=embed)

async def setup(client: commands.Bot) -> None:
  await client.add_cog(drafter_cog(client))